backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "页面"
    files:
      - name: "home"
        label: "首页"
        file: "index.html"
        fields:
          - { name: "title", label: "页面标题", widget: "string" }
          - { name: "body", label: "页面内容", widget: "text" }
